name: CI

on:
  push:
    branches: "**"
  workflow_dispatch:
  issue_comment:
    types: [created, edited]

jobs:
  ci:
    name: CI
    if: >-
      (github.event.issue.pull_request && contains(github.event.comment.body, 'tests:run')) ||
      (github.event_name == 'push' && contains(github.event.head_commit.message, 'tests:run'))
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - run:
          echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV

      - uses: Warpbuilds/action-debugger@v1.3

      # On a psh event, this env var exists: GITHUB_REF
      # On a comment event, GITHUB_REF points to main
      - name: Set PR info for comment triggers
        run: |
          PR_NUMBER="${{ github.event.issue.number }}"
          echo "$PR_NUMBER"
          PR_SHA=$(gh pr view $PR_NUMBER --json headRefOid -q .headRefOid)
          echo "$PR_SHA"
          git checkout $PR_SHA
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Roll
        run:
          #!/usr/bin/env bash
          set -e
          echo "Rolling a d6!"
          roll=(( ( RANDOM % 6 ) + 1 ))
          echo "You rolled a $roll"
          if [ $roll -eq 1 ]; then
            echo "You win!"
            exit 0
          else
            echo "You lose!"
            exit 1
          fi
